### PR TITLE
Redesigning add idea page

### LINKED ISSUE #3: imrpove the ui of add idea page
imrpove the ui of add idea page
it must be matching with theme of team info page

Directories :
chat page : /views/Team-Builder-Dashboard/idea-form/index.html
team info page : /views/Team-Builder-Dashboard/team-info-page/team-info-page.html

### PR DESCRIPTION
**Pull request by Nupoor10**
Fixed #3 

Redesigned the UI of add idea page by taking inspiration from the team info page.

Screenshot : 
redesign

### CODE REVIEW

**Comment by Naresh-chandanbatve** [comment]
hey @Nupoor10 
 can you add the same gradient background as the team info page
 and also the same image as there is in the black division of the team info page

**Comment by Naresh-chandanbatve** [comment]
Screenshot 2023-12-20 150853

like in the screenshot above

**Comment by Nupoor10** [comment]
Sure, I will update the PR today

**Comment by Nupoor10** [comment]
I have updated the design as per the feedback and this is how it looks now : 

Screenshot 2023-12-23 000158

**Review by Naresh-chandanbatve — APPROVED** [review]

**Comment by Naresh-chandanbatve** [comment]
nice work @Nupoor10

**Pull request merged**
