### PR TITLE
Made Sign In and Sign Up Pages responsive.

### PR DESCRIPTION
**Pull request by GauravGupta993**
Made Sign In and Sign Up Pages responsive. #27 
Please tell in case there is any problem. I will work on it. Also since this issue has no difficulty tag attached, is it possible to get medium or higher level tag attached because understanding already written CSS was a challenge and it took me a complete day to understand the already written CSS and make changes to it.

### CODE REVIEW

**Comment by Naresh-chandanbatve** [comment]
hey @GauravGupta993 
Everything is nice and fine
but
it is not redirecting back to sign in page from the register page after clicking the sign in page
can you check the issue
I am adding hard label

**Comment by GauravGupta993** [comment]
> hey @GauravGupta993 Everything is nice and fine but it is not redirecting back to sign in page from the register page after clicking the sign in page can you check the issue I am adding hard label

Will do

**Comment by GauravGupta993** [comment]
Please recheck. I believe issue must have been resolved.

**Comment by GauravGupta993** [comment]
Is this issue completed or do i need to do something else ?

**Comment by Naresh-chandanbatve** [comment]
> Is this issue completed or do i need to do something else ?

it is approved I will merge it 
I am testing some workflows on this pr 👍

**Pull request merged**
